baseurl = "https://yrong.github.io/blog"
title = "yrong blog"
theme = "whiteplain"
languageCode = "en"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2017 Ronyang"

hasCJKLanguage = true

[params]
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Ronyang"
  avatar = "/img/4383920.jpg"
  github = "yrong"
  email = "yrong@ustc.edu"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"